### ISSUE TITLE
Convert to tile map ?

### ISSUE THREAD

**Issue by RUSshy** [redblobgames/mapgen2#1]
Hello

This is impressive stuff, but a bit unusable if i want make a rogue like (tile map) i need to generate a 2d tilemap, i tried to get all point from polygons but it isn't working fine, it create empty spaces

Do you  have an idea ?

Ty!

**Comment by redblobgames** [comment]
Thanks! 

The original project was a tile map game so we converted the polygons to tiles. Two different ways:

1. Draw the biome polygons to an image without anti-aliasing, and turn read the color of each pixel to choose the tile's biome. (For example if the pixel is #ffffff the tile would be snow.) In the original project, I used Flash, which allows drawing polygons while disabling anti-aliasing. HTML5 Canvas doesn't have an option to disable anti-aliasing though, so we would need to use a different library, like @rastapasta's [points-in-polygon](https://github.com/rastapasta/points-in-polygon).
2. Draw the elevations and moisture values to separate images, using gradient fills. Then for each pixel read the elevation and moisture and look up the biome value. This produces smoother biomes (like [this](http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/voronoi-map-goal-smooth.png)). You can either do this with Canvas and read back the pixel data or use libraries like [points-in-triangle](https://github.com/rastapasta/points-in-triangle), or [write your own](http://joshbeam.com/articles/triangle_rasterization/).

In either case you have to handle rivers separately, by drawing lines (Bresenham or similar) in the tile map.

I should add this to the readme.
